services:
  postgres:
    image: postgres:16
    container_name: opd-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - opd-net

  mongo:
    image: mongo:7
    container_name: opd-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - opd-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: opd-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - opd-net
    depends_on:
      - postgres

networks:
  opd-net:

volumes:
  postgres_data:
  mongo_data:
  pgadmin_data:
